### PR TITLE
Release 8.2.0

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Comment by ekohl** [comment]
Can we merge https://github.com/theforeman/puppet-dns/pull/184 before this?

**Comment by ehelms** [comment]
This can now be updated with #184 merged

**Comment by wbclark** [comment]
Updated CHANGELOG.md with #184 and changed release date to Monday April 26th

**Comment by ehelms** [comment]
@ekohl any idea if these test failures are expected?

**Comment by ehelms** [comment]
Current failures are expected

**Review by ehelms — APPROVED** [review]

**Pull request merged**
