### PR TITLE
Added additional_files and additional_config options

### PR DESCRIPTION
**Pull request by msweetser**
I added the options additional_files and additional_config to fill a need of mine using the module.

additional_files will be added as "include" directives, one per file.

additional_config will be added as key value pairs.

### CODE REVIEW

**Comment by ekohl** [comment]
How does ```additional_config``` differ from ```additional_options```? The only difference I see is that it's placed in a different file.

Please also fix the trailing whitespace that's causing the build to fail.

**Comment by ekohl** [comment]
For ```additional_files```, have you considered using ```concat::fragment``` instead?

**Comment by dlucredativ** [comment]
> How does additional_config differ from additional_options? The only difference I see is that it's placed in a different file.

I have a use case for additional_files as well. There are directives that need to go top-scope, like logging, additional keys and such. I was about to create a pull request myself, then I found this one. Can I help somehow? @ekohl, would you rather have the additional_file content included in the named.conf via fragments?

**Comment by ekohl** [comment]
@dlucredativ I'm not against it per se, but I'd like to know the use case and know why the fragments solution would be inadequate.

**Comment by dlucredativ** [comment]
@ekohl, my use case is to configure additional top-scope bind directives (logging, keys). I am fine with `include` statements like in this PR as well as with fragment-based injection into `named.conf`. If it helps the case, I can open another PR with fragments and a fixed travis build. I don't know if @msweetser insists on includes, though.

**Comment by ekohl** [comment]
@dlucredativ if you're managing those additional directives through puppet then I'd suggest you use fragments.

**Comment by dlucredativ** [comment]
@ekohl to be clear, are you suggesting to implement "additional_directives" with `concat::fragment` as a new puppet-dns feature, or to use `concat::fragment` outside of puppet-dns?

**Comment by ekohl** [comment]
@dlucredativ I mostly meant that for uncommon uses to use ```concat::fragment``` outside of puppet-dns, but I think we'd accept a patch that adds ```additional_directives```. However, I think that can be implemented in the main ```named.conf``` with a simple for loop.

**Comment by dlucredativ** [comment]
Alright, I will create a pull request with additional_directives in a few moments.

**Comment by ekohl** [comment]
Closing in favour of #79

**Pull request closed without merging**
