### PR TITLE
Modulesync: require voxpupuli-test 1.2

### PR DESCRIPTION
**Pull request by ekohl**
Follow up on 01d1ede67a89dd3d8e0a2f4edcd9f2de3971735a

### CODE REVIEW

**Comment by ekohl** [comment]
@wbclark why? I don't see any overrides we need.

**Comment by wbclark** [comment]
> @wbclark why? I don't see any overrides we need.

I think I will need some for EL8 but can add the file when that becomes necessary.

By the way, looking at the failed spec tests, it looks to me like facts are not loaded properly. Any idea why?

**Comment by ekohl** [comment]
I spent quite a bit of time to convert testing to rspec-puppet-facts but it's not complete. I did want to push my work though.

**Comment by ekohl** [comment]
This patch turned out much larger than anticipated due to the conversion to rspec-puppet-facts.

**Comment by ekohl** [comment]
:green_heart:

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
