### PR TITLE
allow user to control also-notify on a zone level

### PR DESCRIPTION
**Pull request by wasbo**
Signed-off-by: Warren Clarke <wclarke1@gmail.com>

### CODE REVIEW

**Comment by domcleal** [comment]
:+1: would you also mind adding a test to spec/defines/dns_zone_spec.rb?

**Comment by ekohl** [comment]
A ```validate_array``` in the manifest would also be nice.

**Comment by ekohl** [comment]
You can also include ```Closes GH-43``` in the commit message to automatically close the issue when it's merged.

**Comment by wasbo** [comment]
All requested updates completed :)

**Comment by ekohl** [comment]
:+1: if you can squash both commits we can merge it.

**Comment by wasbo** [comment]
Sorry struggeld to push to squash back to prigin, and ended up deleting the branch, which in turn cl;osed this pull request :(
I have created a new pull request (#45) with the squashed commits. Hope fully that can be merged :)

**Pull request closed without merging**
