### PR TITLE
changed support IRC server from Freenode to Libera

### PR DESCRIPTION
**Pull request by ikonia**
very minor change to readme to list correct IRC server network

### CODE REVIEW

**Comment by evgeni** [comment]
While the change is correct, I wonder if we should mention IRC here at all, vs just saying "go to foreman community".

@ehelms @ekohl thoughts?

**Comment by ekohl** [comment]
Should we link to https://theforeman.org/support.html instead?

**Comment by ikonia** [comment]
is that the consensus ? change the link to the support link rather than the correct IRC link ?

**Comment by evgeni** [comment]
Yes, please

**Comment by ikonia** [comment]
done

**Review by ekohl — APPROVED** [review]
Thanks!

**Pull request merged**
