### PR TITLE
allow additional_options

### PR DESCRIPTION
**Pull request by lobeck**
- adds a hash parameter to allow additional global options to be added to options.conf

### CODE REVIEW

**Comment by ekohl** [comment]
Looks good. Could you set this variable in a test somewhere and verify the output?

**Comment by lobeck** [comment]
Done, but do you have any idea why the build is failing?

**Comment by domcleal** [comment]
It's waiting on a fix in https://github.com/fiddyspence/puppetlint-variablecase/pull/6, sorry!

**Comment by lobeck** [comment]
👍  then let's wait for the fix and we'll see whether my tests works.

**Comment by lobeck** [comment]
finally the test passed. looks like you're killing travis ci ;)

**Comment by domcleal** [comment]
:+1: looks OK.

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
